apiVersion: v1
kind: Pod
metadata:
  name: test-oom
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat <( </dev/zero head -c 100m) <(sleep 120) | tail"]
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "50Mi"
