apiVersion: v1
kind: Pod
metadata:
  name: test-busybox
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "50Mi"
