apiVersion: v1
kind: Pod
metadata:
  name: test-no-image
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: no-image-nf23f23f90
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "50Mi"
