apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
    volumeMounts:
      - mountPath: "/mymnt"
        name: my-mnt
  volumes:
    - name: my-mnt
      persistentVolumeClaim:
        claimName: test-pvc
